/*
 * Copyright (c) 2013, Thomas Barker
 * All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * It under the terms of the GNU General Public License as published by
 * The Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * But WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * Along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "countryCodes.h"

typeof(countryCodes) countryCodes = {
	{'?', '?'},
	{'A', 'D'},
	{'A', 'E'},
	{'A', 'F'},
	{'A', 'G'},
	{'A', 'I'},
	{'A', 'L'},
	{'A', 'M'},
	{'A', 'N'},
	{'A', 'O'},
	{'A', 'R'},
	{'A', 'S'},
	{'A', 'T'},
	{'A', 'U'},
	{'A', 'W'},
	{'A', 'X'},
	{'A', 'Z'},
	{'B', 'A'},
	{'B', 'B'},
	{'B', 'D'},
	{'B', 'E'},
	{'B', 'F'},
	{'B', 'G'},
	{'B', 'H'},
	{'B', 'I'},
	{'B', 'J'},
	{'B', 'M'},
	{'B', 'N'},
	{'B', 'O'},
	{'B', 'R'},
	{'B', 'S'},
	{'B', 'T'},
	{'B', 'V'},
	{'B', 'W'},
	{'B', 'Y'},
	{'B', 'Z'},
	{'C', 'A'},
	{'C', 'C'},
	{'C', 'D'},
	{'C', 'F'},
	{'C', 'G'},
	{'C', 'H'},
	{'C', 'I'},
	{'C', 'K'},
	{'C', 'L'},
	{'C', 'M'},
	{'C', 'N'},
	{'C', 'O'},
	{'C', 'R'},
	{'C', 'S'},
	{'C', 'U'},
	{'C', 'V'},
	{'C', 'X'},
	{'C', 'Y'},
	{'C', 'Z'},
	{'D', 'E'},
	{'D', 'J'},
	{'D', 'K'},
	{'D', 'M'},
	{'D', 'O'},
	{'D', 'Z'},
	{'E', 'C'},
	{'E', 'E'},
	{'E', 'G'},
	{'E', 'H'},
	{'E', 'R'},
	{'E', 'S'},
	{'E', 'T'},
	{'F', 'I'},
	{'F', 'J'},
	{'F', 'K'},
	{'F', 'M'},
	{'F', 'O'},
	{'F', 'R'},
	{'G', 'A'},
	{'G', 'B'},
	{'G', 'D'},
	{'G', 'E'},
	{'G', 'F'},
	{'G', 'H'},
	{'G', 'I'},
	{'G', 'L'},
	{'G', 'M'},
	{'G', 'N'},
	{'G', 'P'},
	{'G', 'Q'},
	{'G', 'R'},
	{'G', 'S'},
	{'G', 'T'},
	{'G', 'U'},
	{'G', 'W'},
	{'G', 'Y'},
	{'H', 'K'},
	{'H', 'M'},
	{'H', 'N'},
	{'H', 'R'},
	{'H', 'T'},
	{'H', 'U'},
	{'I', 'D'},
	{'I', 'E'},
	{'I', 'L'},
	{'I', 'N'},
	{'I', 'O'},
	{'I', 'Q'},
	{'I', 'R'},
	{'I', 'S'},
	{'I', 'T'},
	{'J', 'M'},
	{'J', 'O'},
	{'J', 'P'},
	{'K', 'E'},
	{'K', 'G'},
	{'K', 'H'},
	{'K', 'I'},
	{'K', 'M'},
	{'K', 'N'},
	{'K', 'P'},
	{'K', 'R'},
	{'K', 'W'},
	{'K', 'Y'},
	{'K', 'Z'},
	{'L', 'A'},
	{'L', 'B'},
	{'L', 'C'},
	{'L', 'I'},
	{'L', 'K'},
	{'L', 'R'},
	{'L', 'S'},
	{'L', 'T'},
	{'L', 'U'},
	{'L', 'V'},
	{'L', 'Y'},
	{'M', 'A'},
	{'M', 'C'},
	{'M', 'D'},
	{'M', 'E'},
	{'M', 'G'},
	{'M', 'H'},
	{'M', 'K'},
	{'M', 'L'},
	{'M', 'M'},
	{'M', 'N'},
	{'M', 'O'},
	{'M', 'P'},
	{'M', 'Q'},
	{'M', 'R'},
	{'M', 'S'},
	{'M', 'T'},
	{'M', 'U'},
	{'M', 'V'},
	{'M', 'W'},
	{'M', 'X'},
	{'M', 'Y'},
	{'M', 'Z'},
	{'N', 'A'},
	{'N', 'C'},
	{'N', 'E'},
	{'N', 'F'},
	{'N', 'G'},
	{'N', 'I'},
	{'N', 'L'},
	{'N', 'O'},
	{'N', 'P'},
	{'N', 'R'},
	{'N', 'U'},
	{'N', 'Z'},
	{'O', 'M'},
	{'P', 'A'},
	{'P', 'E'},
	{'P', 'F'},
	{'P', 'G'},
	{'P', 'H'},
	{'P', 'K'},
	{'P', 'L'},
	{'P', 'M'},
	{'P', 'N'},
	{'P', 'R'},
	{'P', 'S'},
	{'P', 'T'},
	{'P', 'W'},
	{'P', 'Y'},
	{'Q', 'A'},
	{'R', 'E'},
	{'R', 'O'},
	{'R', 'S'},
	{'R', 'U'},
	{'R', 'W'},
	{'S', 'A'},
	{'S', 'B'},
	{'S', 'C'},
	{'S', 'D'},
	{'S', 'E'},
	{'S', 'G'},
	{'S', 'H'},
	{'S', 'I'},
	{'S', 'J'},
	{'S', 'K'},
	{'S', 'L'},
	{'S', 'M'},
	{'S', 'N'},
	{'S', 'O'},
	{'S', 'R'},
	{'S', 'T'},
	{'S', 'V'},
	{'S', 'Y'},
	{'S', 'Z'},
	{'T', 'C'},
	{'T', 'D'},
	{'T', 'F'},
	{'T', 'G'},
	{'T', 'H'},
	{'T', 'J'},
	{'T', 'K'},
	{'T', 'L'},
	{'T', 'M'},
	{'T', 'N'},
	{'T', 'O'},
	{'T', 'R'},
	{'T', 'T'},
	{'T', 'V'},
	{'T', 'W'},
	{'T', 'Z'},
	{'U', 'A'},
	{'U', 'G'},
	{'U', 'M'},
	{'U', 'S'},
	{'U', 'Y'},
	{'U', 'Z'},
	{'V', 'A'},
	{'V', 'C'},
	{'V', 'E'},
	{'V', 'G'},
	{'V', 'I'},
	{'V', 'N'},
	{'V', 'U'},
	{'W', 'F'},
	{'W', 'S'},
	{'Y', 'E'},
	{'Y', 'T'},
	{'Z', 'A'},
	{'Z', 'M'},
	{'Z', 'W'},
};

typeof(countryNames) countryNames = {
	"Unknown Country",
	"Andorra",
	"United Arab Emirates",
	"Afghanistan",
	"Antigua And Barbuda",
	"Anguilla",
	"Albania",
	"Armenia",
	"Netherlands Antilles",
	"Angola",
	"Argentina",
	"American Samoa",
	"Austria",
	"Australia",
	"Aruba",
	"Åland Islands",
	"Azerbaijan",
	"Bosnia And Herzegovina",
	"Barbados",
	"Bangladesh",
	"Belgium",
	"Burkina Faso",
	"Bulgaria",
	"Bahrain",
	"Burundi",
	"Benin",
	"Bermuda",
	"Brunei Darussalam",
	"Bolivia, Plurinational State Of",
	"Brazil",
	"Bahamas",
	"Bhutan",
	"Bouvet Island",
	"Botswana",
	"Belarus",
	"Belize",
	"Canada",
	"Cocos (Keeling) Islands",
	"Congo, The Democratic Republic Of The",
	"Central African Republic",
	"Congo",
	"Switzerland",
	"Côte D'Ivoire",
	"Cook Islands",
	"Chile",
	"Cameroon",
	"China",
	"Colombia",
	"Costa Rica",
	"Serbia and Montenegro",
	"Cuba",
	"Cape Verde",
	"Christmas Island",
	"Cyprus",
	"Czech Republic",
	"Germany",
	"Djibouti",
	"Denmark",
	"Dominica",
	"Dominican Republic",
	"Algeria",
	"Ecuador",
	"Estonia",
	"Egypt",
	"Western Sahara",
	"Eritrea",
	"Spain",
	"Ethiopia",
	"Finland",
	"Fiji",
	"Falkland Islands (Malvinas)",
	"Micronesia, Federated States Of",
	"Faroe Islands",
	"France",
	"Gabon",
	"United Kingdom",
	"Grenada",
	"Georgia",
	"French Guiana",
	"Ghana",
	"Gibraltar",
	"Greenland",
	"Gambia",
	"Guinea",
	"Guadeloupe",
	"Equatorial Guinea",
	"Greece",
	"South Georgia And The South Sandwich Islands",
	"Guatemala",
	"Guam",
	"Guinea-Bissau",
	"Guyana",
	"Hong Kong",
	"Heard Island And Mcdonald Islands",
	"Honduras",
	"Croatia",
	"Haiti",
	"Hungary",
	"Indonesia",
	"Ireland",
	"Israel",
	"India",
	"British Indian Ocean Territory",
	"Iraq",
	"Iran, Islamic Republic Of",
	"Iceland",
	"Italy",
	"Jamaica",
	"Jordan",
	"Japan",
	"Kenya",
	"Kyrgyzstan",
	"Cambodia",
	"Kiribati",
	"Comoros",
	"Saint Kitts And Nevis",
	"Korea, Democratic People'S Republic Of",
	"Korea, Republic Of",
	"Kuwait",
	"Cayman Islands",
	"Kazakhstan",
	"Lao People'S Democratic Republic",
	"Lebanon",
	"Saint Lucia",
	"Liechtenstein",
	"Sri Lanka",
	"Liberia",
	"Lesotho",
	"Lithuania",
	"Luxembourg",
	"Latvia",
	"Libyan Arab Jamahiriya",
	"Morocco",
	"Monaco",
	"Moldova, Republic Of",
	"Montenegro",
	"Madagascar",
	"Marshall Islands",
	"Macedonia, The Former Yugoslav Republic Of",
	"Mali",
	"Myanmar",
	"Mongolia",
	"Macao",
	"Northern Mariana Islands",
	"Martinique",
	"Mauritania",
	"Montserrat",
	"Malta",
	"Mauritius",
	"Maldives",
	"Malawi",
	"Mexico",
	"Malaysia",
	"Mozambique",
	"Namibia",
	"New Caledonia",
	"Niger",
	"Norfolk Island",
	"Nigeria",
	"Nicaragua",
	"Netherlands",
	"Norway",
	"Nepal",
	"Nauru",
	"Niue",
	"New Zealand",
	"Oman",
	"Panama",
	"Peru",
	"French Polynesia",
	"Papua New Guinea",
	"Philippines",
	"Pakistan",
	"Poland",
	"Saint Pierre And Miquelon",
	"Pitcairn",
	"Puerto Rico",
	"Palestinian Territory, Occupied",
	"Portugal",
	"Palau",
	"Paraguay",
	"Qatar",
	"Réunion",
	"Romania",
	"Serbia",
	"Russian Federation",
	"Rwanda",
	"Saudi Arabia",
	"Solomon Islands",
	"Seychelles",
	"Sudan",
	"Sweden",
	"Singapore",
	"Saint Helena, Ascension And Tristan Da Cunha",
	"Slovenia",
	"Svalbard And Jan Mayen",
	"Slovakia",
	"Sierra Leone",
	"San Marino",
	"Senegal",
	"Somalia",
	"Suriname",
	"Sao Tome And Principe",
	"El Salvador",
	"Syrian Arab Republic",
	"Swaziland",
	"Turks And Caicos Islands",
	"Chad",
	"French Southern Territories",
	"Togo",
	"Thailand",
	"Tajikistan",
	"Tokelau",
	"Timor-Leste",
	"Turkmenistan",
	"Tunisia",
	"Tonga",
	"Turkey",
	"Trinidad And Tobago",
	"Tuvalu",
	"Taiwan, Province Of China",
	"Tanzania, United Republic Of",
	"Ukraine",
	"Uganda",
	"United States Minor Outlying Islands",
	"United States",
	"Uruguay",
	"Uzbekistan",
	"Holy See (Vatican City State)",
	"Saint Vincent And The Grenadines",
	"Venezuela, Bolivarian Republic Of",
	"Virgin Islands, British",
	"Virgin Islands, U.S.",
	"Viet Nam",
	"Vanuatu",
	"Wallis And Futuna",
	"Samoa",
	"Yemen",
	"Mayotte",
	"South Africa",
	"Zambia",
	"Zimbabwe",
};
