#pragma once
#define INGAME_MASK 1
#define PW_MASK 2
#define FULL_MASK 4
#define USER_MASK 8
#define UNSYNC_MASK 1
#define AWAY_MASK 2
#define IGNORE_MASK 4
enum ICONS {
	ICONS_MASK = 0x0F,

	ICONS_CLOSED,
	ICONS_OPEN,
	
	ICONS_HOST,
	ICONS_SPECTATOR,
	ICONS_HOST_SPECTATOR,
	ICONS_INGAME,
	
	ICONS_FIRST_RANK,
	ICONS_LAST_RANK = ICONS_FIRST_RANK + 7,
	
	ICONS_CONNECTING,
	ICONS_BATTLELIST,
	ICONS_REPLAY,
	ICONS_OPTIONS,
	
	ICONS_SPLIT_VERT,
	ICONS_SPLIT_HORZ,
	ICONS_SPLIT_CORNER1,
	ICONS_SPLIT_CORNER2,
	ICONS_SPLIT_RAND,
	
	ICONS_FIRST_FLAG,
	ICONS_FLAG_COUNT = 240,
	ICONS_LAST_FLAG = ICONS_FIRST_FLAG + ICONS_FLAG_COUNT - 1,

	ICONS_FIRST_SIDE,
	ICONS_SIDE_COUNT = 16,
	ICONS_LAST_SIDE = ICONS_FIRST_SIDE + ICONS_SIDE_COUNT - 1,
	
	ICONS_FIRST_COLOR,
	ICONS_COLOR_COUNT = 32,
	ICONS_LAST_COLOR = ICONS_FIRST_COLOR + ICONS_COLOR_COUNT - 1,
	
	ICONS_LAST = ICONS_LAST_COLOR,
	
	ICONS_READY = ICONS_OPEN,
	ICONS_UNREADY = ICONS_CLOSED,
	
	ICONS_ONLINE = ICONS_OPEN,
	ICONS_OFFLINE = ICONS_CLOSED,
	ICONS_BATTLEROOM = ICONS_INGAME,
	ICONS_HOSTBATTLE = ICONS_HOST,
	ICONS_SINGLEPLAYER = INGAME_MASK,
};

int GetColorIndex(const union UserOrBot *);
#ifdef WINVER
extern HIMAGELIST gIconList;
#endif

#define EnableIcons(window)\
{\
	extern HIMAGELIST gIconList;\
	SendMessage(window, LVM_SETIMAGELIST, LVSIL_SMALL, (LPARAM)gIconList);\
}

#define EnableStateIcons(window)\
{\
	extern HIMAGELIST gIconList;\
	SendMessage(window, LVM_SETIMAGELIST, LVSIL_STATE, (LPARAM)gIconList);\
}
