#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_LOGIN                               103
#define IDD_USERLIST                            112
#define IDR_MENU                                114
#define IDD_CHANGEPASSWORD                      118
#define IDD_HOST                                120
#define IDD_PREFERENCES                         122
#define IDD_AGREEMENT                           124
#define IDD_COLOR                               125
#define IDD_GETTEXT                             126
#define IDD_REPLAY                              132
#define IDD_ABOUT                               134
#define IDD_RAPID                               136
#define IDC_COLOR_R_L1                          1000
#define IDC_PASSWORD_OLD_L                      1000
#define IDC_PREFERENCES_RESET                   1000
#define IDC_ABOUT_EDIT                          1001
#define IDC_AGREEMENT_TEXT                      1001
#define IDC_COLOR_G_L1                          1001
#define IDC_PREFERENCES_AUTOCONNECT             1001
#define IDC_REPLAY_LIST                         1001
#define IDC_COLOR_B_L1                          1002
#define IDC_HOST_MAP_L                          1002
#define IDC_LOGIN_AUTOCONNECT                   1002
#define IDC_HOST_MAP                            1003
#define IDC_LOGIN_SAVE                          1003
#define IDC_USERLIST_LIST                       1003
#define IDC_PASSWORD_CONFIRM_L                  1004
#define IDC_LOGIN_PASSWORD_L                    1005
#define IDC_PASSWORD_NEW_L                      1005
#define IDC_HOST_RELAY                          1006
#define IDC_COLOR_R                             1007
#define IDC_LOGIN_USERNAME                      1007
#define IDC_PREFERENCES_PATH_L                  1007
#define IDC_COLOR_G                             1008
#define IDC_LOGIN_USERNAME_L                    1008
#define IDC_RAPID_SELECT                        1008
#define IDC_COLOR_B                             1009
#define IDC_GETTEXT                             1009
#define IDC_LOGIN_REGISTER                      1009
#define IDC_PASSWORD_OLD                        1009
#define IDC_RAPID_REMOVE                        1009
#define IDC_COLOR_R_L                           1010
#define IDC_PASSWORD_NEW                        1010
#define IDC_COLOR_G_L                           1011
#define IDC_PASSWORD_CONFIRM                    1011
#define IDC_PREFERENCES_PATH                    1011
#define IDC_RAPID_DOWNLOAD                      1011
#define IDC_COLOR_B_L                           1012
#define IDC_HOST_PASSWORD                       1012
#define IDC_HOST_PASSWORD_L                     1013
#define IDC_HOST_DESCRIPTION                    1014
#define IDC_RAPID_SELECTED                      1014
#define IDC_RAPID_AVAILABLE_GROUPBOX            1015
#define IDC_HOST_DESCRIPTION_L                  1016
#define IDC_RAPID_SELECTED_GROUPBOX             1016
#define IDC_COLOR_PREVIEW                       1017
#define IDC_HOST_MOD_L                          1017
#define IDC_RAPID_ERRORCHECK                    1017
#define IDC_RAPID_CLEANUP                       1018
#define IDC_RAPID_AVAILABLE                     1019
#define IDC_LOGIN_PASSWORD                      1020
#define IDM_CONNECT                             40000
#define IDM_QUIT                                40001
#define IDM_DISCONNECT                          40002
#define IDM_SINGLE_PLAYER                       40003
#define IDM_OPEN_CHANNEL                        40004
#define IDM_SPRING_SETTINGS                     40005
#define IDM_ABOUT                               40006
#define IDM_LOBBY_PREFERENCES                   40007
#define IDM_RENAME                              40008
#define IDM_SPRING_RTS                          40009
#define IDM_SPRINGLOBBY                         40010
#define IDM_CHANGE_PASSWORD                     40011
#define IDM_HOST_BATTLE                         40012
#define IDM_SERVER_LOG                          40013
#define IDM_RELOAD_MAPS_MODS                    40014
#define IDM_TASCLIENT                           40015
#define IDM_ZERO_K                              40016
#define IDC_HOST_MOD                            40017
#define IDM_REPLAY                              40017
#define IDM_UPDATE                              40018
#define IDC_HOST_PORT_L                         40021
#define IDC_HOST_PORT                           40022
#define IDC_HOST_USERELAY                       40024
